version: "3.1"
services:
  scheduler:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
      - ./cosmos:/usr/local/airflow/cosmos:rw

  webserver:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
      - ./cosmos:/usr/local/airflow/cosmos:rw

  triggerer:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
      - ./cosmos:/usr/local/airflow/cosmos:rw
