name: 'core'
version: '0.1'
profile: 'my-postgres-db'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  +persist_docs:
    relation: true
    columns: true
    core:
        jaffle_shop:
          +materialized: table



